<Project>`r`n  <PropertyGroup>`r`n    <Version>2026.10.02.1729</Version>`r`n    <AssemblyVersion>2026.10.02.1729</AssemblyVersion>`r`n    <FileVersion>2026.10.02.1729</FileVersion>`r`n    <InformationalVersion>2026.10.02.1729</InformationalVersion>`r`n    <ProductVersion>2026.10.02.1729</ProductVersion>`r`n  </PropertyGroup>`r`n</Project>
